# Generated by Django 2.0.2 on 2020-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categori',
            field=models.ManyToManyField(related_name='get_posts', to='blog.Categori', verbose_name='Categoria'),
        ),
    ]
