# Generated by Django 2.0.2 on 2020-04-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True, verbose_name='Clave')),
                ('name', models.CharField(max_length=25, null=True, verbose_name='Red social')),
                ('url', models.URLField(null=True, verbose_name='URL')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima Actualización')),
            ],
            options={
                'verbose_name': 'Enlace',
                'verbose_name_plural': 'Enlaces',
                'ordering': ['-name'],
            },
        ),
    ]
