# Generated by Django 2.0.2 on 2020-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Título')),
                ('content', models.TextField(null=True, verbose_name='Contenido')),
                ('creado', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('update', models.DateTimeField(auto_now=True, null=True, verbose_name='Ultima Actualización')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Paginas',
                'ordering': ['-creado'],
            },
        ),
    ]
